
pipelines:
  default:
    - step:
        name: 'Build NPM'
        image: node:lts
        script:
          - npm i
        caches:
          - nodemodules
        artifacts:
          - node_modules/**
    - step:
        name: 'Docker build + push to ECR'
        image: python:3.9-alpine
        script:
          - pip3 install -U awscli

          - export BRANCH_TAG=$(echo "$BITBUCKET_BRANCH" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')
          - export REPO=$DOCKER_REPO_URL/kidsloop-sfu-gateway  # DOCKER_REPO_URL is workspace wide variable
          - export COMMIT_TAG=$(git rev-parse --short HEAD)

          - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $DOCKER_REPO_URL
          
          - cp deploy/Dockerfile.bitbucket-pipeline .
          - docker build -t kidsloop-sfu-gateway -f Dockerfile.bitbucket-pipeline .
    
          - docker tag kidsloop-sfu-gateway:latest $REPO:$BRANCH_TAG
          - docker tag kidsloop-sfu-gateway:latest $REPO:$BRANCH_TAG-latest
          - docker tag kidsloop-sfu-gateway:latest $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
          - docker tag kidsloop-sfu-gateway:latest $REPO:$BRANCH_TAG-$COMMIT_TAG

          - docker push $REPO:$BRANCH_TAG
          - docker push $REPO:$BRANCH_TAG-latest
          - docker push $REPO:$BRANCH_TAG-$BITBUCKET_BUILD_NUMBER
          - docker push $REPO:$BRANCH_TAG-$COMMIT_TAG

        services:
          - docker


definitions:
  caches:
    nodemodules: ./node_modules